services:
  web:
    image: 'gitlab/gitlab-ee:latest'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    networks:
      - 'gitlab'

  runner:
    image: 'gitlab/gitlab-runner:latest'
    volumes:
      - './gitlab-runner:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - 'gitlab'

networks:
  gitlab:
    name: 'gitlab-network'
    driver: 'bridge'
