variables:
  GODOT_BUILD_IMAGE: ubuntu:latest
  GODOT_X64_L_BINARY: godot.linuxbsd.opt.tools.64

image: $GODOT_BUILD_IMAGE

stages:
  - build
  - test
  - package

x64.l.build:
  stage: build
  script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get -y install build-essential scons pkg-config libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm
    - scons -j8 platform=linuxbsd bits=64 target=release_debug tools=yes tests=yes
  artifacts:
    paths:
      - bin/

x64.l.test:
  stage: test
  script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get -y install build-essential scons pkg-config libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm
    - ./bin/$GODOT_X64_L_BINARY --test

x64.l.package:
  stage: package
  script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get -y install zip
    - zip -j $GODOT_X64_L_BINARY.zip bin/$GODOT_X64_L_BINARY
  artifacts:
    paths:
      - $GODOT_X64_L_BINARY.zip
